version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec puma -C config/puma.rb -e development -p 3000
    environment:
      - DATABASE_PASSWORD=password
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-data: