default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: 
  pool: 5

development:
  <<: *default
  database: Rubyist-connect_development

test:
  <<: *default
  database: Rubyist-connect_test
