default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  username: <%= ENV.fetch('DATABASE_USERNAME', '') %>
  password: 
  pool: 5

development:
  <<: *default
  database: Rubyist-connect_development

test:
  <<: *default
  database: Rubyist-connect_test
